"""update tables5

Revision ID: 7f1f6e139311
Revises: 01a4b42a5f6d
Create Date: 2025-09-04 21:53:42.492313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7f1f6e139311'
down_revision: Union[str, Sequence[str], None] = '01a4b42a5f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
